/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-rate-limit/limited": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RateLimitTestController_getLimited"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-rate-limit/unlimited": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RateLimitTestController_getUnlimited"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-rate-limit/limited-with-option": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RateLimitTestController_getLimitedWithOption"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/painting/tag/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Retrieve a single Tag */
        get: operations["getOneBaseTagControllerTag"];
        put?: never;
        post?: never;
        /** Delete a single Tag */
        delete: operations["deleteOneBaseTagControllerTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/painting/tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve multiple Tags.
         * @description use join field, If want Painting[]. you can filter by painting properties like id, title and image_url
         *
         *     Example:
         *     ```
         *     GET backend/tag?s={"name":{"$cont":"female"}}&join=paintings
         *     ```
         */
        get: operations["getManyBaseTagControllerTag"];
        put: operations["TagController_replace"];
        post: operations["TagController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/security-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_generateSecurityActionToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/security-token/email-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_sendSecurityActionToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/security-token/from-email-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_generateSecurityTokenByEmailVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/emailTest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_sendEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/test/one-time-token-guard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_testSecurityTokenGuard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/one-time-token/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["AuthController_getOneTimeToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Retrieve a single User */
        get: operations["getOneBaseUserControllerUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve multiple Users */
        get: operations["getManyBaseUserControllerUser"];
        put?: never;
        /** Create a single User */
        post: operations["createOneBaseUserControllerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{email}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["UserController_replacePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{email}/username": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["UserController_replaceUsername"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{email}/role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["UserController_replaceRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["UserController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/recover/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserController_recoverUser"];
        trace?: never;
    };
    "/painting/style/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Retrieve single Style by id. */
        get: operations["getOneBaseStyleControllerStyle"];
        /** Replace a single Style */
        put: operations["replaceOneBaseStyleControllerStyle"];
        post?: never;
        /** Delete a single Style */
        delete: operations["deleteOneBaseStyleControllerStyle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/painting/style": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve multiple Styles.
         * @description use join field, If want Painting[]. you can filter by painting properties like id, title and image_url
         *
         *     Example:
         *     ```
         *     GET backend/style?s={"name":{"$cont":"female"}}&join=paintings
         *     ```
         */
        get: operations["getManyBaseStyleControllerStyle"];
        put?: never;
        /** Create a single Style */
        post: operations["createOneBaseStyleControllerStyle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/painting/by-ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * retrieve multiple paintings by id
         * @description {domain}/painting/by-ids?ids=id1&id2&id3
         *     Example:
         *     ```
         *     GET backend/painting/by-ids?ids=409ba4c6-0553-4b72-a53a-d9b9857c253d&ids=4f4d9398-b10a-45b8-912c-6ccd0c6700ab
         *     ```
         */
        get: operations["PaintingController_getByIds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/painting/artwork-of-week": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaintingController_getWeeklyArtworkData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/painting/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["PaintingController_getById"];
        put: operations["PaintingController_replacePainting"];
        post?: never;
        delete: operations["PaintingController_deletePainting"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/painting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaintingController_searchPainting"];
        put?: never;
        post: operations["PaintingController_createPainting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artist/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Retrieve Artist by id. */
        get: operations["getOneBaseArtistControllerArtist"];
        /** Replace a single Artist */
        put: operations["replaceOneBaseArtistControllerArtist"];
        post?: never;
        /** Delete a single Artist */
        delete: operations["deleteOneBaseArtistControllerArtist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve multiple Artist
         * @description use join field, If want Painting[]. you can filter by painting properties id, title and image_url
         *
         *     Example:
         *     ```
         *     GET backend/artist?s={"name":{"$cont":"Leonardo"}}&join=paintings
         *     ```
         */
        get: operations["getManyBaseArtistControllerArtist"];
        put?: never;
        /** Create a single Artist */
        post: operations["createOneBaseArtistControllerArtist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s3/{bucket}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket: string;
            };
            cookie?: never;
        };
        get: operations["S3Controller_readFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quiz/submit/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["QuizController_submitQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quiz/{id}/reactions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["QuizController_getQuizReactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quiz/{id}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["QuizController_createQuizReaction"];
        delete: operations["QuizController_deleteQuizReaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quiz/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["QuizController_getScheduledQuiz"];
        put?: never;
        post: operations["QuizController_addQuizContext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["QuizController_searchQuiz"];
        put?: never;
        post: operations["QuizController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quiz/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Retrieve a single Quiz */
        get: operations["getOneBaseQuizControllerQuiz"];
        put: operations["QuizController_update"];
        post?: never;
        delete: operations["QuizController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        ShortPaintingResponse: {
            id: string;
            title: string;
            image_url: string;
            width: number;
            height: number;
        };
        ShowTagResponse: {
            id: string;
            name: string;
            info_url: string | null;
            shortPaintings?: components["schemas"]["ShortPaintingResponse"][];
        };
        Pagination: {
            data: string[];
            count: number;
            total: number;
            page: number;
            pageCount: number;
        };
        CreateTagDTO: {
            name: string;
        };
        ReplaceTagDTO: {
            info_url: string;
            name: string;
        };
        GetManyTagResponseDto: {
            data: components["schemas"]["Tag"][];
            count: number;
            total: number;
            page: number;
            pageCount: number;
        };
        Tag: Record<string, never>;
        ShowUserResponse: {
            /** @enum {string} */
            role: ShowUserResponseRole;
            /** @enum {string} */
            active: ShowUserResponseActive;
            id: string;
            email: string;
            username: string;
            /** Format: date-time */
            last_login_date: string;
            oauth_provider: string | null;
            oauth_provider_id: string | null;
        };
        SignInResponse: {
            accessToken: string;
            refreshToken: string;
            user: components["schemas"]["ShowUserResponse"];
        };
        requestVerificationDTO: {
            email: string;
        };
        ShowVerificationResponse: {
            id: string;
            /** Format: date-time */
            verification_success_date: string | null;
            /** Format: date-time */
            last_verified_date: string | null;
            pin_code: string;
            /** Format: date-time */
            pin_code_expired_date: string;
        };
        VerifyDTO: {
            pinCode: string;
            email: string;
        };
        ShowOneTimeTokenResponse: {
            /** @enum {string} */
            purpose: ShowOneTimeTokenResponsePurpose;
            id: string;
            token: string;
            /** Format: date-time */
            used_date: string | null;
            /** Format: date-time */
            expired_date: string;
        };
        CreateOneTimeTokenDTO: {
            /** @enum {string} */
            purpose: CreateOneTimeTokenDTOPurpose;
        };
        SendOneTimeTokenDTO: {
            /** @enum {string} */
            purpose: SendOneTimeTokenDTOPurpose;
            email: string;
        };
        CreateUserDTO: {
            oauth_provider?: string;
            oauth_provider_id?: string;
            password: string;
            username: string;
        };
        ReplacePassWordDTO: {
            password: string;
        };
        ReplaceUsernameDTO: {
            username: string;
        };
        ReplaceRoleDTO: {
            /** @enum {string} */
            role: ReplaceRoleDTORole;
        };
        GetManyUserResponseDto: {
            data: components["schemas"]["User"][];
            count: number;
            total: number;
            page: number;
            pageCount: number;
        };
        User: Record<string, never>;
        ShowStyleResponse: {
            id: string;
            name: string;
            info_url: string | null;
            shortPaintings?: components["schemas"]["ShortPaintingResponse"][];
        };
        CreateStyleDTO: {
            name: string;
        };
        ReplaceStyleDTO: {
            info_url: string;
            name: string;
        };
        GetManyStyleResponseDto: {
            data: components["schemas"]["Style"][];
            count: number;
            total: number;
            page: number;
            pageCount: number;
        };
        Style: Record<string, never>;
        ShowTag: {
            id: string;
            name: string;
            info_url: string | null;
        };
        ShowStyle: {
            id: string;
            name: string;
            info_url: string | null;
        };
        ShowArtist: {
            id: string;
            name: string;
            image_url: string;
            /** Format: date-time */
            birth_date: string;
            /** Format: date-time */
            death_date: string;
            info_url: string;
        };
        ShowPaintingResponse: {
            showTags?: components["schemas"]["ShowTag"][];
            showStyles?: components["schemas"]["ShowStyle"][];
            showArtist?: components["schemas"]["ShowArtist"][];
            id: string;
            title: string;
            image_url: string;
            description: string;
            completition_year: number;
            width: number;
            height: number;
        };
        CreatePaintingDTO: {
            artistName?: string;
            width?: number;
            height?: number;
            completition_year?: number;
            tags?: string[];
            styles?: string[];
            image_s3_key?: string;
            title: string;
            image_url: string;
            description: string;
        };
        ReplacePaintingDTO: {
            artistName?: string;
            width?: number;
            height?: number;
            completition_year?: number;
            image_s3_key?: string;
            tags: string[];
            styles: string[];
            title: string;
            image_url: string;
            description: string;
        };
        ShowArtistResponse: {
            id: string;
            name: string;
            image_url: string;
            /** Format: date-time */
            birth_date: string;
            /** Format: date-time */
            death_date: string;
            info_url: string;
            shortPaintings?: components["schemas"]["ShortPaintingResponse"][];
        };
        CreateArtistDTO: {
            /** Format: date-time */
            birth_date?: string;
            /** Format: date-time */
            death_date?: string;
            info_url?: string;
            image_url?: string;
            name: string;
        };
        GetManyArtistResponseDto: {
            data: components["schemas"]["Artist"][];
            count: number;
            total: number;
            page: number;
            pageCount: number;
        };
        Artist: Record<string, never>;
        QuizSubmitDTO: {
            isCorrect: boolean;
        };
        QuizReactionDTO: {
            /** @enum {string} */
            type: QuizReactionDTOType;
        };
        QuizContextDTO: {
            artist?: string;
            tag?: string;
            style?: string;
            page: number;
            _atLeastOne: Record<string, never>;
        };
        ShortQuizResponse: {
            id: string;
            title: string;
            time_limit: number;
            /** Format: date-time */
            created_date: string;
            /** Format: date-time */
            updated_date: string;
            showOwner: components["schemas"]["ShowUserResponse"];
        };
        QuizResponse: {
            shortQuiz: components["schemas"]["ShortQuizResponse"];
            status: Record<string, never>;
        };
        CreateQuizDTO: {
            examplePaintingId?: string;
            /** @enum {string} */
            type: CreateQuizDTOType;
            answerPaintingIds: string[];
            distractorPaintingIds: string[];
            title: string;
            timeLimit: number;
            description: string;
        };
        ShowQuizResponse: {
            showOwner: components["schemas"]["ShowUserResponse"];
        };
        GetManyQuizResponseDto: {
            data: components["schemas"]["Quiz"][];
            count: number;
            total: number;
            page: number;
            pageCount: number;
        };
        Quiz: Record<string, never>;
        QuizReactionCount: Record<string, never>;
        DetailQuizResponse: {
            quiz: components["schemas"]["ShowQuizResponse"];
            reactionCount: components["schemas"]["QuizReactionCount"];
            userReaction?: Record<string, never>;
        };
        UpdateQuizDTO: {
            examplePaintingId?: string;
            answerPaintingIds: string[];
            distractorPaintingIds: string[];
            title: string;
            timeLimit: number;
            description: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type ShortPaintingResponse = components['schemas']['ShortPaintingResponse'];
export type ShowTagResponse = components['schemas']['ShowTagResponse'];
export type Pagination = components['schemas']['Pagination'];
export type CreateTagDto = components['schemas']['CreateTagDTO'];
export type ReplaceTagDto = components['schemas']['ReplaceTagDTO'];
export type GetManyTagResponseDto = components['schemas']['GetManyTagResponseDto'];
export type Tag = components['schemas']['Tag'];
export type ShowUserResponse = components['schemas']['ShowUserResponse'];
export type SignInResponse = components['schemas']['SignInResponse'];
export type RequestVerificationDto = components['schemas']['requestVerificationDTO'];
export type ShowVerificationResponse = components['schemas']['ShowVerificationResponse'];
export type VerifyDto = components['schemas']['VerifyDTO'];
export type ShowOneTimeTokenResponse = components['schemas']['ShowOneTimeTokenResponse'];
export type CreateOneTimeTokenDto = components['schemas']['CreateOneTimeTokenDTO'];
export type SendOneTimeTokenDto = components['schemas']['SendOneTimeTokenDTO'];
export type CreateUserDto = components['schemas']['CreateUserDTO'];
export type ReplacePassWordDto = components['schemas']['ReplacePassWordDTO'];
export type ReplaceUsernameDto = components['schemas']['ReplaceUsernameDTO'];
export type ReplaceRoleDto = components['schemas']['ReplaceRoleDTO'];
export type GetManyUserResponseDto = components['schemas']['GetManyUserResponseDto'];
export type User = components['schemas']['User'];
export type ShowStyleResponse = components['schemas']['ShowStyleResponse'];
export type CreateStyleDto = components['schemas']['CreateStyleDTO'];
export type ReplaceStyleDto = components['schemas']['ReplaceStyleDTO'];
export type GetManyStyleResponseDto = components['schemas']['GetManyStyleResponseDto'];
export type Style = components['schemas']['Style'];
export type ShowTag = components['schemas']['ShowTag'];
export type ShowStyle = components['schemas']['ShowStyle'];
export type ShowArtist = components['schemas']['ShowArtist'];
export type ShowPaintingResponse = components['schemas']['ShowPaintingResponse'];
export type CreatePaintingDto = components['schemas']['CreatePaintingDTO'];
export type ReplacePaintingDto = components['schemas']['ReplacePaintingDTO'];
export type ShowArtistResponse = components['schemas']['ShowArtistResponse'];
export type CreateArtistDto = components['schemas']['CreateArtistDTO'];
export type GetManyArtistResponseDto = components['schemas']['GetManyArtistResponseDto'];
export type Artist = components['schemas']['Artist'];
export type QuizSubmitDto = components['schemas']['QuizSubmitDTO'];
export type QuizReactionDto = components['schemas']['QuizReactionDTO'];
export type QuizContextDto = components['schemas']['QuizContextDTO'];
export type ShortQuizResponse = components['schemas']['ShortQuizResponse'];
export type QuizResponse = components['schemas']['QuizResponse'];
export type CreateQuizDto = components['schemas']['CreateQuizDTO'];
export type ShowQuizResponse = components['schemas']['ShowQuizResponse'];
export type GetManyQuizResponseDto = components['schemas']['GetManyQuizResponseDto'];
export type Quiz = components['schemas']['Quiz'];
export type QuizReactionCount = components['schemas']['QuizReactionCount'];
export type DetailQuizResponse = components['schemas']['DetailQuizResponse'];
export type UpdateQuizDto = components['schemas']['UpdateQuizDTO'];
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    RateLimitTestController_getLimited: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RateLimitTestController_getUnlimited: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RateLimitTestController_getLimitedWithOption: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOneBaseTagControllerTag: {
        parameters: {
            query?: {
                /** @description Selects resource fields. <a href="https://github.com/nestjsx/crud/wiki/Requests#select" target="_blank">Docs</a> */
                fields?: string[];
                /** @description Adds relational resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#join" target="_blank">Docs</a> */
                join?: string[];
                /** @description Reset cache (if was enabled). <a href="https://github.com/nestjsx/crud/wiki/Requests#cache" target="_blank">Docs</a> */
                cache?: number;
                /** @description Include deleted. <a href="https://github.com/nestjsx/crud/wiki/Requests#includeDeleted" target="_blank">Docs</a> */
                include_deleted?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowTagResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowTagResponse"];
                };
            };
        };
    };
    deleteOneBaseTagControllerTag: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getManyBaseTagControllerTag: {
        parameters: {
            query?: {
                /** @description Selects resource fields. <a href="https://github.com/nestjsx/crud/wiki/Requests#select" target="_blank">Docs</a> */
                fields?: string[];
                /** @description Adds search condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#search" target="_blank">Docs</a> */
                s?: string;
                /** @description Adds filter condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#filter" target="_blank">Docs</a> */
                filter?: string[];
                /** @description Adds OR condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#or" target="_blank">Docs</a> */
                or?: string[];
                /** @description Adds sort by field. <a href="https://github.com/nestjsx/crud/wiki/Requests#sort" target="_blank">Docs</a> */
                sort?: string[];
                /** @description Adds relational resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#join" target="_blank">Docs</a> */
                join?: string[];
                /** @description Limit amount of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#limit" target="_blank">Docs</a> */
                limit?: number;
                /** @description Offset amount of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#offset" target="_blank">Docs</a> */
                offset?: number;
                /** @description Page portion of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#page" target="_blank">Docs</a> */
                page?: number;
                /** @description Reset cache (if was enabled). <a href="https://github.com/nestjsx/crud/wiki/Requests#cache" target="_blank">Docs</a> */
                cache?: number;
                /** @description Include deleted. <a href="https://github.com/nestjsx/crud/wiki/Requests#includeDeleted" target="_blank">Docs</a> */
                include_deleted?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data?: components["schemas"]["ShowTagResponse"][];
                    };
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data?: components["schemas"]["ShowTagResponse"][];
                    };
                };
            };
        };
    };
    TagController_replace: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceTagDTO"];
            };
        };
        responses: {
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowTagResponse"];
                };
            };
        };
    };
    TagController_create: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagDTO"];
            };
        };
        responses: {
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowTagResponse"];
                };
            };
        };
    };
    AuthController_signin: {
        parameters: {
            query?: never;
            header: {
                /** @description account authorization header.  */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Authorized Account */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["requestVerificationDTO"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowVerificationResponse"];
                };
            };
        };
    };
    AuthController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyDTO"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowOneTimeTokenResponse"];
                };
            };
        };
    };
    AuthController_generateSecurityActionToken: {
        parameters: {
            query?: never;
            header: {
                /** @description account authorization header.  */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOneTimeTokenDTO"];
            };
        };
        responses: {
            /** @description Not Authorized Account */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowOneTimeTokenResponse"];
                };
            };
        };
    };
    AuthController_sendSecurityActionToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendOneTimeTokenDTO"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_generateSecurityTokenByEmailVerification: {
        parameters: {
            query?: never;
            header?: {
                /** @description oneTimeToken issued for security purpose */
                "x-one-time-token-value"?: string;
                /** @description oneTimeToken identifier */
                "x-one-time-token-identifier"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOneTimeTokenDTO"];
            };
        };
        responses: {
            /** @description Not Authorized oneTimeToken */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowOneTimeTokenResponse"];
                };
            };
        };
    };
    AuthController_sendEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    AuthController_testSecurityTokenGuard: {
        parameters: {
            query?: never;
            header?: {
                /** @description oneTimeToken issued for security purpose */
                "x-one-time-token-value"?: string;
                /** @description oneTimeToken identifier */
                "x-one-time-token-identifier"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Authorized oneTimeToken */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getOneTimeToken: {
        parameters: {
            query?: never;
            header: {
                /** @description account authorization header.  */
                authorization: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Authorized Account */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not own the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowOneTimeTokenResponse"];
                };
            };
        };
    };
    getOneBaseUserControllerUser: {
        parameters: {
            query?: {
                /** @description Selects resource fields. <a href="https://github.com/nestjsx/crud/wiki/Requests#select" target="_blank">Docs</a> */
                fields?: string[];
                /** @description Adds relational resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#join" target="_blank">Docs</a> */
                join?: string[];
                /** @description Reset cache (if was enabled). <a href="https://github.com/nestjsx/crud/wiki/Requests#cache" target="_blank">Docs</a> */
                cache?: number;
                /** @description Include deleted. <a href="https://github.com/nestjsx/crud/wiki/Requests#includeDeleted" target="_blank">Docs</a> */
                include_deleted?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowUserResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowUserResponse"];
                };
            };
        };
    };
    getManyBaseUserControllerUser: {
        parameters: {
            query?: {
                /** @description Selects resource fields. <a href="https://github.com/nestjsx/crud/wiki/Requests#select" target="_blank">Docs</a> */
                fields?: string[];
                /** @description Adds search condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#search" target="_blank">Docs</a> */
                s?: string;
                /** @description Adds filter condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#filter" target="_blank">Docs</a> */
                filter?: string[];
                /** @description Adds OR condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#or" target="_blank">Docs</a> */
                or?: string[];
                /** @description Adds sort by field. <a href="https://github.com/nestjsx/crud/wiki/Requests#sort" target="_blank">Docs</a> */
                sort?: string[];
                /** @description Adds relational resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#join" target="_blank">Docs</a> */
                join?: string[];
                /** @description Limit amount of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#limit" target="_blank">Docs</a> */
                limit?: number;
                /** @description Offset amount of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#offset" target="_blank">Docs</a> */
                offset?: number;
                /** @description Page portion of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#page" target="_blank">Docs</a> */
                page?: number;
                /** @description Reset cache (if was enabled). <a href="https://github.com/nestjsx/crud/wiki/Requests#cache" target="_blank">Docs</a> */
                cache?: number;
                /** @description Include deleted. <a href="https://github.com/nestjsx/crud/wiki/Requests#includeDeleted" target="_blank">Docs</a> */
                include_deleted?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data?: components["schemas"]["ShowUserResponse"][];
                    };
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data?: components["schemas"]["ShowUserResponse"][];
                    };
                };
            };
        };
    };
    createOneBaseUserControllerUser: {
        parameters: {
            query?: never;
            header?: {
                /** @description oneTimeToken issued for security purpose */
                "x-one-time-token-value"?: string;
                /** @description oneTimeToken identifier */
                "x-one-time-token-identifier"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowUserResponse"];
                };
            };
            /** @description Not Authorized oneTimeToken for temp user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowUserResponse"];
                };
            };
        };
    };
    UserController_replacePassword: {
        parameters: {
            query?: never;
            header?: {
                /** @description oneTimeToken issued for security purpose */
                "x-one-time-token-value"?: string;
                /** @description oneTimeToken identifier */
                "x-one-time-token-identifier"?: string;
            };
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplacePassWordDTO"];
            };
        };
        responses: {
            /** @description Not Authorized oneTimeToken */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not own the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_replaceUsername: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceUsernameDTO"];
            };
        };
        responses: {
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not own the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_replaceRole: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceRoleDTO"];
            };
        };
        responses: {
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_deleteUser: {
        parameters: {
            query?: never;
            header?: {
                /** @description oneTimeToken issued for security purpose */
                "x-one-time-token-value"?: string;
                /** @description oneTimeToken identifier */
                "x-one-time-token-identifier"?: string;
            };
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Authorized oneTimeToken */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not own the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_recoverUser: {
        parameters: {
            query?: never;
            header?: {
                /** @description oneTimeToken issued for security purpose */
                "x-one-time-token-value"?: string;
                /** @description oneTimeToken identifier */
                "x-one-time-token-identifier"?: string;
            };
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Authorized oneTimeToken */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not own the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOneBaseStyleControllerStyle: {
        parameters: {
            query?: {
                /** @description Selects resource fields. <a href="https://github.com/nestjsx/crud/wiki/Requests#select" target="_blank">Docs</a> */
                fields?: string[];
                /** @description Adds relational resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#join" target="_blank">Docs</a> */
                join?: string[];
                /** @description Reset cache (if was enabled). <a href="https://github.com/nestjsx/crud/wiki/Requests#cache" target="_blank">Docs</a> */
                cache?: number;
                /** @description Include deleted. <a href="https://github.com/nestjsx/crud/wiki/Requests#includeDeleted" target="_blank">Docs</a> */
                include_deleted?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowStyleResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowStyleResponse"];
                };
            };
        };
    };
    replaceOneBaseStyleControllerStyle: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceStyleDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowStyleResponse"];
                };
            };
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowStyleResponse"];
                };
            };
        };
    };
    deleteOneBaseStyleControllerStyle: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getManyBaseStyleControllerStyle: {
        parameters: {
            query?: {
                /** @description Selects resource fields. <a href="https://github.com/nestjsx/crud/wiki/Requests#select" target="_blank">Docs</a> */
                fields?: string[];
                /** @description Adds search condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#search" target="_blank">Docs</a> */
                s?: string;
                /** @description Adds filter condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#filter" target="_blank">Docs</a> */
                filter?: string[];
                /** @description Adds OR condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#or" target="_blank">Docs</a> */
                or?: string[];
                /** @description Adds sort by field. <a href="https://github.com/nestjsx/crud/wiki/Requests#sort" target="_blank">Docs</a> */
                sort?: string[];
                /** @description Adds relational resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#join" target="_blank">Docs</a> */
                join?: string[];
                /** @description Limit amount of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#limit" target="_blank">Docs</a> */
                limit?: number;
                /** @description Offset amount of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#offset" target="_blank">Docs</a> */
                offset?: number;
                /** @description Page portion of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#page" target="_blank">Docs</a> */
                page?: number;
                /** @description Reset cache (if was enabled). <a href="https://github.com/nestjsx/crud/wiki/Requests#cache" target="_blank">Docs</a> */
                cache?: number;
                /** @description Include deleted. <a href="https://github.com/nestjsx/crud/wiki/Requests#includeDeleted" target="_blank">Docs</a> */
                include_deleted?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data?: components["schemas"]["ShowStyleResponse"][];
                    };
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data?: components["schemas"]["ShowStyleResponse"][];
                    };
                };
            };
        };
    };
    createOneBaseStyleControllerStyle: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStyleDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowStyleResponse"];
                };
            };
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowStyleResponse"];
                };
            };
        };
    };
    PaintingController_getByIds: {
        parameters: {
            query: {
                ids: string[];
                isS3Access: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowPaintingResponse"][];
                };
            };
        };
    };
    PaintingController_getWeeklyArtworkData: {
        parameters: {
            query: {
                isS3Access: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowPaintingResponse"][];
                };
            };
        };
    };
    PaintingController_getById: {
        parameters: {
            query: {
                isS3Access: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowPaintingResponse"];
                };
            };
        };
    };
    PaintingController_replacePainting: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplacePaintingDTO"];
            };
        };
        responses: {
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowPaintingResponse"];
                };
            };
        };
    };
    PaintingController_deletePainting: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaintingController_searchPainting: {
        parameters: {
            query: {
                title?: string;
                artistName?: string;
                tags?: string[];
                styles?: string[];
                page: number;
                isS3Access: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data?: components["schemas"]["ShortPaintingResponse"][];
                    };
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data?: components["schemas"]["ShortPaintingResponse"][];
                    };
                };
            };
        };
    };
    PaintingController_createPainting: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaintingDTO"];
            };
        };
        responses: {
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowPaintingResponse"];
                };
            };
        };
    };
    getOneBaseArtistControllerArtist: {
        parameters: {
            query?: {
                /** @description Selects resource fields. <a href="https://github.com/nestjsx/crud/wiki/Requests#select" target="_blank">Docs</a> */
                fields?: string[];
                /** @description Adds relational resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#join" target="_blank">Docs</a> */
                join?: string[];
                /** @description Reset cache (if was enabled). <a href="https://github.com/nestjsx/crud/wiki/Requests#cache" target="_blank">Docs</a> */
                cache?: number;
                /** @description Include deleted. <a href="https://github.com/nestjsx/crud/wiki/Requests#includeDeleted" target="_blank">Docs</a> */
                include_deleted?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowArtistResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowArtistResponse"];
                };
            };
        };
    };
    replaceOneBaseArtistControllerArtist: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArtistDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowArtistResponse"];
                };
            };
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowArtistResponse"];
                };
            };
        };
    };
    deleteOneBaseArtistControllerArtist: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getManyBaseArtistControllerArtist: {
        parameters: {
            query?: {
                /** @description Selects resource fields. <a href="https://github.com/nestjsx/crud/wiki/Requests#select" target="_blank">Docs</a> */
                fields?: string[];
                /** @description Adds search condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#search" target="_blank">Docs</a> */
                s?: string;
                /** @description Adds filter condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#filter" target="_blank">Docs</a> */
                filter?: string[];
                /** @description Adds OR condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#or" target="_blank">Docs</a> */
                or?: string[];
                /** @description Adds sort by field. <a href="https://github.com/nestjsx/crud/wiki/Requests#sort" target="_blank">Docs</a> */
                sort?: string[];
                /** @description Adds relational resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#join" target="_blank">Docs</a> */
                join?: string[];
                /** @description Limit amount of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#limit" target="_blank">Docs</a> */
                limit?: number;
                /** @description Offset amount of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#offset" target="_blank">Docs</a> */
                offset?: number;
                /** @description Page portion of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#page" target="_blank">Docs</a> */
                page?: number;
                /** @description Reset cache (if was enabled). <a href="https://github.com/nestjsx/crud/wiki/Requests#cache" target="_blank">Docs</a> */
                cache?: number;
                /** @description Include deleted. <a href="https://github.com/nestjsx/crud/wiki/Requests#includeDeleted" target="_blank">Docs</a> */
                include_deleted?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data?: components["schemas"]["ShowArtistResponse"][];
                    };
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data?: components["schemas"]["ShowArtistResponse"][];
                    };
                };
            };
        };
    };
    createOneBaseArtistControllerArtist: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArtistDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowArtistResponse"];
                };
            };
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowArtistResponse"];
                };
            };
        };
    };
    S3Controller_readFile: {
        parameters: {
            query: {
                key: string;
                destination: string;
            };
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                bucket: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed User's role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    QuizController_submitQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizSubmitDTO"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    QuizController_getQuizReactions: {
        parameters: {
            query: {
                type: PathsQuizIdReactionsGetParametersQueryType;
                user_id?: string;
                page?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    QuizController_createQuizReaction: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizReactionDTO"];
            };
        };
        responses: {
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    QuizController_deleteQuizReaction: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    QuizController_getScheduledQuiz: {
        parameters: {
            query?: {
                currentIndex?: number;
                endIndex?: number;
                context?: components["schemas"]["QuizContextDTO"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponse"];
                };
            };
        };
    };
    QuizController_addQuizContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizContextDTO"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    QuizController_searchQuiz: {
        parameters: {
            query: {
                artists?: string[];
                tags?: string[];
                styles?: string[];
                page: number;
                count: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data?: components["schemas"]["ShortQuizResponse"][];
                    };
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data?: components["schemas"]["ShortQuizResponse"][];
                    };
                };
            };
        };
    };
    QuizController_create: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuizDTO"];
            };
        };
        responses: {
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowQuizResponse"];
                };
            };
        };
    };
    getOneBaseQuizControllerQuiz: {
        parameters: {
            query: {
                isS3Access: boolean;
                /** @description Selects resource fields. <a href="https://github.com/nestjsx/crud/wiki/Requests#select" target="_blank">Docs</a> */
                fields?: string[];
                /** @description Adds relational resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#join" target="_blank">Docs</a> */
                join?: string[];
                /** @description Reset cache (if was enabled). <a href="https://github.com/nestjsx/crud/wiki/Requests#cache" target="_blank">Docs</a> */
                cache?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get one base response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailQuizResponse"];
                };
            };
        };
    };
    QuizController_update: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuizDTO"];
            };
        };
        responses: {
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not own the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowQuizResponse"];
                };
            };
        };
    };
    QuizController_delete: {
        parameters: {
            query?: never;
            header: {
                /** @description bear authorization header */
                authorization: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Authorized Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not own the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
export enum PathsQuizIdReactionsGetParametersQueryType {
    like = "like",
    dislike = "dislike"
}
export enum ShowUserResponseRole {
    admin = "admin",
    user = "user"
}
export enum ShowUserResponseActive {
    active = "active",
    inactive = "inactive",
    banned = "banned"
}
export enum ShowOneTimeTokenResponsePurpose {
    update_password = "update-password",
    delete_account = "delete-account",
    magic_login = "magic-login",
    sign_up = "sign-up",
    email_verification = "email-verification",
    recover_account = "recover-account"
}
export enum CreateOneTimeTokenDTOPurpose {
    update_password = "update-password",
    delete_account = "delete-account",
    magic_login = "magic-login",
    sign_up = "sign-up",
    email_verification = "email-verification",
    recover_account = "recover-account"
}
export enum SendOneTimeTokenDTOPurpose {
    update_password = "update-password",
    recover_account = "recover-account"
}
export enum ReplaceRoleDTORole {
    admin = "admin",
    user = "user"
}
export enum QuizReactionDTOType {
    like = "like",
    dislike = "dislike"
}
export enum CreateQuizDTOType {
    ONE_CHOICE = "ONE_CHOICE",
    MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
    TRUE_FALSE = "TRUE_FALSE"
}
export enum ApiPaths {
    AppController_getHello = "/",
    RateLimitTestController_getLimited = "/test-rate-limit/limited",
    RateLimitTestController_getUnlimited = "/test-rate-limit/unlimited",
    RateLimitTestController_getLimitedWithOption = "/test-rate-limit/limited-with-option",
    getOneBaseTagControllerTag = "/painting/tag/{id}",
    deleteOneBaseTagControllerTag = "/painting/tag/{id}",
    getManyBaseTagControllerTag = "/painting/tag",
    TagController_create = "/painting/tag",
    TagController_replace = "/painting/tag",
    AuthController_signin = "/auth/sign-in",
    AuthController_register = "/auth/request-verification",
    AuthController_verify = "/auth/verify",
    AuthController_generateSecurityActionToken = "/auth/security-token",
    AuthController_sendSecurityActionToken = "/auth/security-token/email-verification",
    AuthController_generateSecurityTokenByEmailVerification = "/auth/security-token/from-email-verification",
    AuthController_sendEmail = "/auth/emailTest",
    AuthController_testSecurityTokenGuard = "/auth/test/one-time-token-guard",
    AuthController_getOneTimeToken = "/auth/one-time-token/{id}",
    getOneBaseUserControllerUser = "/user/{id}",
    getManyBaseUserControllerUser = "/user",
    createOneBaseUserControllerUser = "/user",
    UserController_replacePassword = "/user/{email}/password",
    UserController_replaceUsername = "/user/{email}/username",
    UserController_replaceRole = "/user/{email}/role",
    UserController_deleteUser = "/user/{email}",
    UserController_recoverUser = "/user/recover/{email}",
    getOneBaseStyleControllerStyle = "/painting/style/{id}",
    replaceOneBaseStyleControllerStyle = "/painting/style/{id}",
    deleteOneBaseStyleControllerStyle = "/painting/style/{id}",
    getManyBaseStyleControllerStyle = "/painting/style",
    createOneBaseStyleControllerStyle = "/painting/style",
    PaintingController_getByIds = "/painting/by-ids",
    PaintingController_getWeeklyArtworkData = "/painting/artwork-of-week",
    PaintingController_getById = "/painting/{id}",
    PaintingController_replacePainting = "/painting/{id}",
    PaintingController_deletePainting = "/painting/{id}",
    PaintingController_searchPainting = "/painting",
    PaintingController_createPainting = "/painting",
    getOneBaseArtistControllerArtist = "/artist/{id}",
    replaceOneBaseArtistControllerArtist = "/artist/{id}",
    deleteOneBaseArtistControllerArtist = "/artist/{id}",
    getManyBaseArtistControllerArtist = "/artist",
    createOneBaseArtistControllerArtist = "/artist",
    S3Controller_readFile = "/s3/{bucket}",
    QuizController_submitQuiz = "/quiz/submit/{id}",
    QuizController_getQuizReactions = "/quiz/{id}/reactions",
    QuizController_createQuizReaction = "/quiz/{id}/reaction",
    QuizController_deleteQuizReaction = "/quiz/{id}/reaction",
    QuizController_getScheduledQuiz = "/quiz/schedule",
    QuizController_addQuizContext = "/quiz/schedule",
    QuizController_create = "/quiz",
    QuizController_searchQuiz = "/quiz",
    getOneBaseQuizControllerQuiz = "/quiz/{id}",
    QuizController_update = "/quiz/{id}",
    QuizController_delete = "/quiz/{id}"
}
