name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: andyjm7739/ggrim
          stage: main
          yaml: |
            name: ggrim-back-main
            app: dockerfile
            options:
              ports: "3000"
              dockerfile: Dockerfile
              uid: "1000"
              gid: "1000"
              env: []
              args:
                - name: GPG_TOKEN
                  secret: backend-gpg-password
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}